backend:
  name: git-gateway
  branch: main

media_folder: "public/imagens/uploads"
public_folder: "/imagens/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/content/posts/animes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Resumo", name: "description", widget: "text" }
      - { label: "Imagem", name: "image", widget: "image" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }